# Generated by Django 3.0.6 on 2020-05-14 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Active', models.BooleanField(default=True)),
                ('Phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.ImageField(default='../media/profilepic/user.png', upload_to='../media/profilepic/')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.User')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('cv', models.FileField(blank=True, default=None, null=True, upload_to='../media/cv/')),
            ],
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=300, unique=True)),
                ('Start_date', models.DateTimeField(default=datetime.datetime(2020, 5, 14, 1, 26, 36, 804952, tzinfo=utc))),
                ('End_date', models.DateTimeField(default=datetime.datetime(2020, 5, 21, 1, 26, 36, 804980, tzinfo=utc))),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.User')),
                ('relate_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Doctor')),
            ],
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../media/cases/default.jpeg', upload_to='../media/cases/')),
                ('case_name', models.CharField(max_length=100)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(max_length=50)),
                ('relate_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Patient')),
            ],
        ),
    ]
