# Generated by Django 3.0.3 on 2020-04-02 22:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=300, unique=True)),
                ('Start_date', models.DateTimeField(default=datetime.datetime(2020, 4, 2, 22, 58, 14, 33083, tzinfo=utc))),
                ('End_date', models.DateTimeField(default=datetime.datetime(2020, 4, 9, 22, 58, 14, 33083, tzinfo=utc))),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
