# Generated by Django 3.0.3 on 2020-04-02 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='End_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 17, 41, 43, 310325, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='Start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 17, 41, 43, 310325, tzinfo=utc)),
        ),
    ]
