# Generated by Django 3.0.5 on 2020-05-14 20:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200514_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='relate_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='relate_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Doctor'),
        ),
        migrations.AlterField(
            model_name='token',
            name='End_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 20, 44, 36, 960681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='Start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 20, 44, 36, 960681, tzinfo=utc)),
        ),
    ]
