# Generated by Django 3.0.3 on 2020-04-06 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200403_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='End_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 3, 35, 47, 650667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='Start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 3, 35, 47, 650667, tzinfo=utc)),
        ),
    ]
