# Generated by Django 3.0.5 on 2020-04-02 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200402_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='End_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 22, 33, 23, 61756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='Start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 22, 33, 23, 61756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
