# Generated by Django 3.0.5 on 2020-04-02 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200403_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='End_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 22, 34, 23, 606705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='Start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 22, 34, 23, 606705, tzinfo=utc)),
        ),
    ]
